-- Salon policy "non-working days" labels.

INSERT INTO translations (key, locale, value) VALUES
    ('policy.nonWorkingDays',             'en', 'Non-working days'),
    ('policy.nonWorkingDays',             'rs', 'Neradni dani'),
    ('policy.nonWorkingDaysHelp',         'en', 'Mark specific days, date ranges or week days when the salon is closed. No appointments are offered on these days.'),
    ('policy.nonWorkingDaysHelp',         'rs', 'Označi konkretne dane, datumske periode ili dane u nedelji kada je salon zatvoren. Tih dana se ne nude termini.'),
    ('policy.nonWorkingDayDate',          'en', 'Date'),
    ('policy.nonWorkingDayDate',          'rs', 'Datum'),
    ('policy.nonWorkingDayReason',        'en', 'Reason (optional)'),
    ('policy.nonWorkingDayReason',        'rs', 'Razlog (opciono)'),
    ('policy.addNonWorkingDay',           'en', 'Add day'),
    ('policy.addNonWorkingDay',           'rs', 'Dodaj dan'),
    ('policy.addNonWorkingRange',         'en', 'Add range'),
    ('policy.addNonWorkingRange',         'rs', 'Dodaj period'),
    ('policy.nonWorkingDayInvalid',       'en', 'Enter a valid date (YYYY-MM-DD).'),
    ('policy.nonWorkingDayInvalid',       'rs', 'Unesite važeći datum (GGGG-MM-DD).'),
    ('policy.nonWorkingDayInvalidRange',  'en', 'End date must be on or after the start date.'),
    ('policy.nonWorkingDayInvalidRange',  'rs', 'Krajnji datum mora biti na ili posle početnog datuma.'),
    ('policy.nonWorkingDaysEmpty',        'en', 'No non-working days yet.'),
    ('policy.nonWorkingDaysEmpty',        'rs', 'Još nema neradnih dana.'),
    ('policy.nonWorkingDaysSingle',       'en', 'Single day'),
    ('policy.nonWorkingDaysSingle',       'rs', 'Jedan dan'),
    ('policy.nonWorkingDaysMultiple',     'en', 'Multiple days'),
    ('policy.nonWorkingDaysMultiple',     'rs', 'Više dana'),
    ('policy.nonWorkingDaysWeekly',       'en', 'Week days'),
    ('policy.nonWorkingDaysWeekly',       'rs', 'Dani u nedelji'),
    ('policy.nonWorkingDaysWeeklyHelp',   'en', 'These days are closed every week.'),
    ('policy.nonWorkingDaysWeeklyHelp',   'rs', 'Ovi dani su zatvoreni svake nedelje.'),
    ('policy.nonWorkingDayRepeatYearly',  'en', 'Repeat every year'),
    ('policy.nonWorkingDayRepeatYearly',  'rs', 'Ponavlja se svake godine'),
    ('policy.nonWorkingDayRangeStart',    'en', 'From'),
    ('policy.nonWorkingDayRangeStart',    'rs', 'Od'),
    ('policy.nonWorkingDayRangeEnd',      'en', 'To'),
    ('policy.nonWorkingDayRangeEnd',      'rs', 'Do'),
    ('policy.nonWorkingDayEveryYear',     'en', 'every year'),
    ('policy.nonWorkingDayEveryYear',     'rs', 'svake godine');
