-- Booking flow labels.

INSERT INTO translations (key, locale, value) VALUES
    ('booking.step.service',        'en', 'Choose a service'),
    ('booking.step.barber',         'en', 'Choose your barber'),
    ('booking.step.date',           'en', 'Pick a date'),
    ('booking.step.time',           'en', 'Pick a time'),
    ('booking.confirm.title',       'en', 'Confirm your booking'),
    ('booking.confirm.service',     'en', 'Service'),
    ('booking.confirm.barber',      'en', 'Barber'),
    ('booking.confirm.date',        'en', 'Date'),
    ('booking.confirm.time',        'en', 'Time'),
    ('booking.confirm.price',       'en', 'Price'),
    ('booking.confirm.button',      'en', 'Confirm booking'),
    ('booking.empty.barbers',       'en', 'No barbers offer this service yet.'),
    ('booking.empty.slots',         'en', 'No availability on this day.'),
    ('booking.success.title',       'en', 'Appointment booked!'),
    ('booking.success.body',        'en', 'See you soon.'),
    ('booking.error.taken',         'en', 'That time was just taken. Please pick another.'),
    ('booking.error.alreadyBooked', 'en', 'You already have a booking with this salon today.'),
    ('booking.error.noService',     'en', 'This barber doesn''t offer this service. Please pick another.'),
    ('booking.error.generic',       'en', 'Booking failed. Please try again.'),

    ('booking.step.service',        'rs', 'Izaberite uslugu'),
    ('booking.step.barber',         'rs', 'Izaberite berberina'),
    ('booking.step.date',           'rs', 'Izaberite datum'),
    ('booking.step.time',           'rs', 'Izaberite vreme'),
    ('booking.confirm.title',       'rs', 'Potvrdite rezervaciju'),
    ('booking.confirm.service',     'rs', 'Usluga'),
    ('booking.confirm.barber',      'rs', 'Berberin'),
    ('booking.confirm.date',        'rs', 'Datum'),
    ('booking.confirm.time',        'rs', 'Vreme'),
    ('booking.confirm.price',       'rs', 'Cena'),
    ('booking.confirm.button',      'rs', 'Potvrdi rezervaciju'),
    ('booking.empty.barbers',       'rs', 'Nijedan berberin još ne nudi ovu uslugu.'),
    ('booking.empty.slots',         'rs', 'Nema slobodnih termina ovog dana.'),
    ('booking.success.title',       'rs', 'Termin je rezervisan!'),
    ('booking.success.body',        'rs', 'Vidimo se uskoro.'),
    ('booking.error.taken',         'rs', 'Taj termin je upravo zauzet. Izaberite drugi.'),
    ('booking.error.alreadyBooked', 'rs', 'Već imate rezervaciju u ovom salonu danas.'),
    ('booking.error.noService',     'rs', 'Ovaj berberin ne nudi ovu uslugu. Izaberite drugog.'),
    ('booking.error.generic',       'rs', 'Rezervacija nije uspela. Pokušajte ponovo.');
