-- App-wide UI labels extracted from the frontend into the translations table.
-- English (en) and Serbian (rs) as before. Keys with {placeholders} are
-- interpolated on the frontend.

INSERT INTO translations (key, locale, value) VALUES
    -- Common buttons / terms.
    ('common.loading', 'en', 'Loading…'),
    ('common.loading', 'rs', 'Učitavanje…'),
    ('common.cancel',  'en', 'Cancel'),
    ('common.cancel',  'rs', 'Odustani'),
    ('common.back',    'en', 'Back'),
    ('common.back',    'rs', 'Nazad'),
    ('common.save',    'en', 'Save'),
    ('common.save',    'rs', 'Sačuvaj'),
    ('common.saving',  'en', 'Saving…'),
    ('common.saving',  'rs', 'Čuvanje…'),
    ('common.done',    'en', 'Done'),
    ('common.done',    'rs', 'Gotovo'),
    ('common.edit',    'en', 'Edit'),
    ('common.edit',    'rs', 'Izmeni'),
    ('common.delete',  'en', 'Delete'),
    ('common.delete',  'rs', 'Obriši'),
    ('common.close',   'en', 'Close'),
    ('common.close',   'rs', 'Zatvori'),
    ('common.remove',  'en', 'Remove'),
    ('common.remove',  'rs', 'Ukloni'),
    ('common.logIn',   'en', 'Log in'),
    ('common.logIn',   'rs', 'Prijavi se'),
    ('common.register','en', 'Register'),
    ('common.register','rs', 'Registruj se'),
    ('common.name',    'en', 'Name'),
    ('common.name',    'rs', 'Ime'),
    ('common.email',   'en', 'Email'),
    ('common.email',   'rs', 'Email'),
    ('common.more',    'en', '+{count} more'),
    ('common.more',    'rs', '+{count} još'),

    -- Top app bar / navigation.
    ('app.welcome',         'en', 'Welcome {name}'),
    ('app.welcome',         'rs', 'Dobrodošli {name}'),
    ('app.allSalons',       'en', 'All salons'),
    ('app.allSalons',       'rs', 'Svi saloni'),
    ('app.logout',          'en', 'Logout'),
    ('app.logout',          'rs', 'Odjavi se'),
    ('app.uploadAvatar',    'en', 'Upload profile picture'),
    ('app.uploadAvatar',    'rs', 'Otpremi profilnu sliku'),
    ('app.goHome',          'en', 'Go to home page'),
    ('app.goHome',          'rs', 'Idi na početnu stranicu'),
    ('nav.home',            'en', 'Home'),
    ('nav.home',            'rs', 'Početna'),
    ('nav.services',        'en', 'Services'),
    ('nav.services',        'rs', 'Usluge'),
    ('nav.barbers',         'en', 'Barbers'),
    ('nav.barbers',         'rs', 'Berberi'),
    ('nav.book',            'en', 'Book'),
    ('nav.book',            'rs', 'Rezerviši'),
    ('nav.myAppointments',  'en', 'My appointments'),
    ('nav.myAppointments',  'rs', 'Moji termini'),
    ('nav.myReservations',  'en', 'My reservations'),
    ('nav.myReservations',  'rs', 'Moje rezervacije'),
    ('nav.reserveMyTime',   'en', 'Reserve my time'),
    ('nav.reserveMyTime',   'rs', 'Rezerviši svoje vreme'),

    -- Home page.
    ('home.intro', 'en', 'Book haircut appointments. Open a salon from a list below.'),
    ('home.intro', 'rs', 'Zakažite termine šišanja. Otvorite salon putem liste ispod.'),

    -- Salon shell.
    ('salon.notFound', 'en', 'Salon not found'),
    ('salon.notFound', 'rs', 'Salon nije pronađen'),
    ('salon.policy',   'en', 'Salon policy'),
    ('salon.policy',   'rs', 'Politika salona'),
    ('salon.rename',   'en', 'Rename'),
    ('salon.rename',   'rs', 'Preimenuj'),
    ('salon.owner',    'en', 'owner'),
    ('salon.owner',    'rs', 'vlasnik'),

    -- Landing page / section editing.
    ('landing.addSection', 'en', 'Add section'),
    ('landing.addSection', 'rs', 'Dodaj sekciju'),
    ('sections.hero',      'en', 'Hero'),
    ('sections.hero',      'rs', 'Hero'),
    ('sections.about',     'en', 'About'),
    ('sections.about',     'rs', 'O nama'),
    ('sections.gallery',   'en', 'Gallery'),
    ('sections.gallery',   'rs', 'Galerija'),
    ('sections.contact',   'en', 'Contact'),
    ('sections.contact',   'rs', 'Kontakt'),
    ('sections.editor.title', 'en', 'Edit {type} section'),
    ('sections.editor.title', 'rs', 'Izmeni {type} sekciju'),
    ('sections.editor.livePreview', 'en', 'Live preview'),
    ('sections.editor.livePreview', 'rs', 'Pregled uživo'),
    ('sections.form.headline',       'en', 'Headline'),
    ('sections.form.headline',       'rs', 'Naslov'),
    ('sections.form.subheadline',    'en', 'Subheadline'),
    ('sections.form.subheadline',    'rs', 'Podnaslov'),
    ('sections.form.ctaText',        'en', 'CTA text'),
    ('sections.form.ctaText',        'rs', 'Tekst dugmeta'),
    ('sections.form.logo',           'en', 'Logo'),
    ('sections.form.logo',           'rs', 'Logo'),
    ('sections.form.background',     'en', 'Background'),
    ('sections.form.background',     'rs', 'Pozadina'),
    ('sections.form.heading',        'en', 'Heading'),
    ('sections.form.heading',        'rs', 'Naslov'),
    ('sections.form.body',           'en', 'Body'),
    ('sections.form.body',           'rs', 'Tekst'),
    ('sections.form.images',         'en', 'Images'),
    ('sections.form.images',         'rs', 'Slike'),
    ('sections.form.phone',          'en', 'Phone'),
    ('sections.form.phone',          'rs', 'Telefon'),
    ('sections.form.address',        'en', 'Address'),
    ('sections.form.address',        'rs', 'Adresa'),
    ('sections.form.googleReviewUrl','en', 'Google review URL'),
    ('sections.form.googleReviewUrl','rs', 'URL Google recenzije'),
    ('sections.form.instagramUrl',   'en', 'Instagram URL'),
    ('sections.form.instagramUrl',   'rs', 'Instagram URL'),
    ('sections.form.uploadLogo',     'en', 'Upload logo'),
    ('sections.form.uploadLogo',     'rs', 'Otpremi logo'),
    ('sections.form.uploadBackground','en', 'Upload background'),
    ('sections.form.uploadBackground','rs', 'Otpremi pozadinu'),
    ('sections.form.addImage',       'en', 'Add image'),
    ('sections.form.addImage',       'rs', 'Dodaj sliku'),
    ('sections.form.removeImage',    'en', 'Remove image'),
    ('sections.form.removeImage',    'rs', 'Ukloni sliku'),
    ('sections.form.addressPlaceholder', 'en', 'Street, city, country'),
    ('sections.form.addressPlaceholder', 'rs', 'Ulica, grad, država'),
    ('sections.contact.leaveRating', 'en', 'Leave a rating'),
    ('sections.contact.leaveRating', 'rs', 'Ostavite ocenu'),

    -- Services page + forms.
    ('services.title',        'en', 'Services'),
    ('services.title',        'rs', 'Usluge'),
    ('services.add',          'en', 'Add service'),
    ('services.add',          'rs', 'Dodaj uslugu'),
    ('services.loadError',    'en', 'Couldn''t load services. Please try again.'),
    ('services.loadError',    'rs', 'Usluge nisu mogle da se učitaju. Pokušajte ponovo.'),
    ('services.empty',        'en', 'No services available at this time.'),
    ('services.empty',        'rs', 'Trenutno nema dostupnih usluga.'),
    ('services.saveError',    'en', 'Failed to save service.'),
    ('services.saveError',    'rs', 'Čuvanje usluge nije uspelo.'),
    ('services.deleteError',  'en', 'Failed to delete service.'),
    ('services.deleteError',  'rs', 'Brisanje usluge nije uspelo.'),
    ('services.deleteTitle',  'en', 'Delete service'),
    ('services.deleteTitle',  'rs', 'Obriši uslugu'),
    ('services.deleteConfirm','en', 'Delete "{name}"? This can''t be undone.'),
    ('services.deleteConfirm','rs', 'Obrisati "{name}"? Ova radnja se ne može poništiti.'),
    ('services.bookNow',      'en', 'Book now'),
    ('services.bookNow',      'rs', 'Rezerviši sada'),
    ('services.editTitle',    'en', 'Edit service'),
    ('services.editTitle',    'rs', 'Izmeni uslugu'),
    ('services.addTitle',     'en', 'Add service'),
    ('services.addTitle',     'rs', 'Dodaj uslugu'),
    ('services.fields.description', 'en', 'Description'),
    ('services.fields.description', 'rs', 'Opis'),
    ('services.fields.duration',    'en', 'Duration (minutes)'),
    ('services.fields.duration',    'rs', 'Trajanje (minuti)'),
    ('services.fields.price',       'en', 'Price ($)'),
    ('services.fields.price',       'rs', 'Cena ($)'),
    ('services.fields.barbers',     'en', 'Barbers'),
    ('services.fields.barbers',     'rs', 'Berberi'),
    ('services.fields.picture',     'en', 'Picture'),
    ('services.fields.picture',     'rs', 'Slika'),
    ('services.noBarbers',   'en', 'No barbers yet. Invite barbers from the Barbers page.'),
    ('services.noBarbers',   'rs', 'Još nema berbera. Pozovite berbere sa stranice Berberi.'),
    ('services.previewName', 'en', 'Service name'),
    ('services.previewName', 'rs', 'Naziv usluge'),
    ('services.livePreview', 'en', 'Live preview'),
    ('services.livePreview', 'rs', 'Pregled uživo'),
    ('services.replaceImage','en', 'Replace image'),
    ('services.replaceImage','rs', 'Zameni sliku'),
    ('services.addImage',    'en', 'Add image'),
    ('services.addImage',    'rs', 'Dodaj sliku'),
    ('services.you',         'en', 'You'),
    ('services.you',         'rs', 'Vi'),
    ('services.barber',      'en', 'Barber'),
    ('services.barber',      'rs', 'Berberin'),

    -- Barbers page + form.
    ('barbers.title',       'en', 'Barbers'),
    ('barbers.title',       'rs', 'Berberi'),
    ('barbers.invite',      'en', 'Invite'),
    ('barbers.invite',      'rs', 'Pozovi'),
    ('barbers.add',         'en', 'Add barber'),
    ('barbers.add',         'rs', 'Dodaj berberina'),
    ('barbers.loadError',   'en', 'Couldn''t load barbers. Please try again.'),
    ('barbers.loadError',   'rs', 'Berberi nisu mogli da se učitaju. Pokušajte ponovo.'),
    ('barbers.empty',       'en', 'No barbers listed yet.'),
    ('barbers.empty',       'rs', 'Još nema navedenih berbera.'),
    ('barbers.inviteError', 'en', 'Couldn''t generate an invite link. Please try again.'),
    ('barbers.inviteError', 'rs', 'Nije moguće generisati link za poziv. Pokušajte ponovo.'),
    ('barbers.removeTitle', 'en', 'Remove barber'),
    ('barbers.removeTitle', 'rs', 'Ukloni berberina'),
    ('barbers.removeConfirm','en', 'Remove {name}? Their upcoming bookings will be reassigned or cancelled.'),
    ('barbers.removeConfirm','rs', 'Ukloniti {name}? Njihovi naredni termini će biti preraspoređeni ili otkazani.'),
    ('barbers.removed',     'en', 'Employee removed.'),
    ('barbers.removed',     'rs', 'Berberin je uklonjen.'),
    ('barbers.reassigned',  'en', '{count} upcoming booking{plural} reassigned'),
    ('barbers.reassigned',  'rs', '{count} narednih termina preraspoređeno'),
    ('barbers.cancelled',   'en', '{count} cancelled'),
    ('barbers.cancelled',   'rs', '{count} otkazano'),
    ('barberForm.avatarTitle',  'en', 'Barber avatar'),
    ('barberForm.avatarTitle',  'rs', 'Avatar berberina'),
    ('barberForm.addTitle',     'en', 'Add barber'),
    ('barberForm.addTitle',     'rs', 'Dodaj berberina'),
    ('barberForm.uploadAvatar', 'en', 'Upload avatar'),
    ('barberForm.uploadAvatar', 'rs', 'Otpremi avatar'),
    ('barberForm.noServices',   'en', 'No services yet.'),
    ('barberForm.noServices',   'rs', 'Još nema usluga.'),
    ('barberForm.inviting',     'en', 'Inviting…'),
    ('barberForm.inviting',     'rs', 'Pozivanje…'),
    ('barberForm.fields.services','en', 'Services'),
    ('barberForm.fields.services','rs', 'Usluge'),
    ('barberForm.fields.avatar',  'en', 'Avatar'),
    ('barberForm.fields.avatar',  'rs', 'Avatar'),

    -- Invite dialog + landing.
    ('invite.title',       'en', 'Invite link'),
    ('invite.title',       'rs', 'Link za poziv'),
    ('invite.help',        'en', 'Share this link or QR code. Scanning it lets someone join this salon as an employee.'),
    ('invite.help',        'rs', 'Podelite ovaj link ili QR kod. Skeniranjem se neko može pridružiti ovom salonu kao zaposleni.'),
    ('invite.generating',  'en', 'Generating…'),
    ('invite.generating',  'rs', 'Generisanje…'),
    ('invite.copied',      'en', 'Copied'),
    ('invite.copied',      'rs', 'Kopirano'),
    ('invite.copyLink',    'en', 'Copy link'),
    ('invite.copyLink',    'rs', 'Kopiraj link'),
    ('invite.downloadQR',  'en', 'Download QR'),
    ('invite.downloadQR',  'rs', 'Preuzmi QR'),
    ('invite.expires',     'en', 'Single use · expires {date}'),
    ('invite.expires',     'rs', 'Za jednokratnu upotrebu · ističe {date}'),
    ('invite.landing.loading',     'en', 'Loading invitation…'),
    ('invite.landing.loading',     'rs', 'Učitavanje pozivnice…'),
    ('invite.landing.unavailable', 'en', 'Invite unavailable'),
    ('invite.landing.unavailable', 'rs', 'Pozivnica nije dostupna'),
    ('invite.landing.invalid',     'en', 'This invite link is invalid, has already been used, or has expired.'),
    ('invite.landing.invalid',     'rs', 'Ovaj link za poziv je nevažeći, već iskorišćen ili je istekao.'),
    ('invite.landing.joining',     'en', 'Joining {salon}…'),
    ('invite.landing.joining',     'rs', 'Pridružujete se salonu {salon}…'),
    ('invite.landing.redirect',    'en', 'You''ll be redirected shortly.'),
    ('invite.landing.redirect',    'rs', 'Uskoro ćete biti preusmereni.'),
    ('invite.landing.invitedTo',   'en', 'You''ve been invited to {salon}'),
    ('invite.landing.invitedTo',   'rs', 'Pozvani ste u salon {salon}'),
    ('invite.landing.joinPrompt',  'en', 'Register or log in to join this salon.'),
    ('invite.landing.joinPrompt',  'rs', 'Registrujte se ili se prijavite da se pridružite salonu.'),
    ('invite.landing.noApp',       'en', 'Don''t have the app?'),
    ('invite.landing.noApp',       'rs', 'Nemate aplikaciju?'),

    -- Booking page.
    ('booking.title',      'en', 'Booking'),
    ('booking.title',      'rs', 'Rezervacija'),
    ('booking.duration',   'en', 'Duration'),
    ('booking.duration',   'rs', 'Trajanje'),
    ('booking.minutes',    'en', 'min'),
    ('booking.minutes',    'rs', 'min'),
    ('booking.loginToBook','en', 'Login to book'),
    ('booking.loginToBook','rs', 'Prijavite se da rezervišete'),
    ('booking.booking',    'en', 'Booking…'),
    ('booking.booking',    'rs', 'Rezervisanje…'),

    -- Customer appointments.
    ('appointments.title',          'en', 'My Appointments'),
    ('appointments.title',          'rs', 'Moji termini'),
    ('appointments.loginPrompt',    'en', 'Please log in to view your appointments.'),
    ('appointments.loginPrompt',    'rs', 'Prijavite se da vidite svoje termine.'),
    ('appointments.empty',          'en', 'No appointments yet.'),
    ('appointments.empty',          'rs', 'Još nema termina.'),
    ('appointments.cancelled',      'en', 'Appointment cancelled.'),
    ('appointments.cancelled',      'rs', 'Termin je otkazan.'),
    ('appointments.cancelFailed',   'en', 'Failed to cancel appointment.'),
    ('appointments.cancelFailed',   'rs', 'Otkazivanje termina nije uspelo.'),
    ('appointments.cancelTitle',    'en', 'Cancel appointment'),
    ('appointments.cancelTitle',    'rs', 'Otkaži termin'),
    ('appointments.cancelling',     'en', 'Cancelling…'),
    ('appointments.cancelling',     'rs', 'Otkazivanje…'),
    ('appointments.reasonLabel',    'en', 'Reason (optional)'),
    ('appointments.reasonLabel',    'rs', 'Razlog (opciono)'),
    ('appointments.reasonPlaceholder','en', 'Why are you cancelling?'),
    ('appointments.reasonPlaceholder','rs', 'Zašto otkazujete?'),
    ('appointments.durationStatus', 'en', 'Duration: {duration} min · Status: {status}'),
    ('appointments.durationStatus', 'rs', 'Trajanje: {duration} min · Status: {status}'),
    ('appointments.reason',         'en', 'Reason: {reason}'),
    ('appointments.reason',         'rs', 'Razlog: {reason}'),
    ('appointments.deadlinePassed', 'en', 'Cancellation deadline has passed'),
    ('appointments.deadlinePassed', 'rs', 'Rok za otkazivanje je prošao'),
    ('appointments.noticeRequired', 'en', '{hours}h notice required'),
    ('appointments.noticeRequired', 'rs', 'potrebno {hours}h najave'),

    -- Reservation statuses.
    ('status.pending',   'en', 'pending'),
    ('status.pending',   'rs', 'na čekanju'),
    ('status.confirmed', 'en', 'confirmed'),
    ('status.confirmed', 'rs', 'potvrđen'),
    ('status.completed', 'en', 'completed'),
    ('status.completed', 'rs', 'završen'),
    ('status.cancelled', 'en', 'cancelled'),
    ('status.cancelled', 'rs', 'otkazan'),
    ('status.no_show',   'en', 'no-show'),
    ('status.no_show',   'rs', 'nepojavljivanje'),

    -- Employee self-service schedule.
    ('schedule.title',            'en', 'My Schedule'),
    ('schedule.title',            'rs', 'Moj raspored'),
    ('schedule.loginPrompt',      'en', 'Please log in to manage your schedule.'),
    ('schedule.loginPrompt',      'rs', 'Prijavite se da upravljate svojim rasporedom.'),
    ('schedule.reserveTitle',     'en', 'Reserve a time slot'),
    ('schedule.reserveTitle',     'rs', 'Rezerviši termin'),
    ('schedule.reserveHint',      'en', 'Reserved slots are hidden from customers, so they cannot book during this time.'),
    ('schedule.reserveHint',      'rs', 'Rezervisani termini su sakriveni od klijenata, pa ne mogu rezervisati u tom periodu.'),
    ('schedule.date',             'en', 'Date'),
    ('schedule.date',             'rs', 'Datum'),
    ('schedule.startTime',        'en', 'Start time'),
    ('schedule.startTime',        'rs', 'Vreme početka'),
    ('schedule.endTime',          'en', 'End time'),
    ('schedule.endTime',          'rs', 'Vreme kraja'),
    ('schedule.reasonOptional',   'en', 'Reason (optional)'),
    ('schedule.reasonOptional',   'rs', 'Razlog (opciono)'),
    ('schedule.reasonPlaceholder','en', 'e.g. urgent errand'),
    ('schedule.reasonPlaceholder','rs', 'npr. hitan zadatak'),
    ('schedule.reserving',        'en', 'Reserving...'),
    ('schedule.reserving',        'rs', 'Rezervisanje...'),
    ('schedule.reserveSlot',      'en', 'Reserve slot'),
    ('schedule.reserveSlot',      'rs', 'Rezerviši termin'),
    ('schedule.endAfterStart',    'en', 'End time must be after start time.'),
    ('schedule.endAfterStart',    'rs', 'Vreme kraja mora biti posle vremena početka.'),
    ('schedule.reserved',         'en', 'Time slot reserved.'),
    ('schedule.reserved',         'rs', 'Termin je rezervisan.'),
    ('schedule.reserveFailed',    'en', 'Failed to reserve. The slot may already be blocked.'),
    ('schedule.reserveFailed',    'rs', 'Rezervacija nije uspela. Termin je možda već blokiran.'),
    ('schedule.removed',          'en', 'Blocked slot removed.'),
    ('schedule.removed',          'rs', 'Blokirani termin je uklonjen.'),
    ('schedule.removeFailed',     'en', 'Failed to remove blocked slot.'),
    ('schedule.removeFailed',     'rs', 'Uklanjanje blokiranog termina nije uspelo.'),
    ('schedule.reservedSlots',    'en', 'Reserved time slots'),
    ('schedule.reservedSlots',    'rs', 'Rezervisani termini'),
    ('schedule.noReserved',       'en', 'No reserved time slots.'),
    ('schedule.noReserved',       'rs', 'Nema rezervisanih termina.'),
    ('schedule.awaitingApproval', 'en', 'awaiting approval'),
    ('schedule.awaitingApproval', 'rs', 'čeka odobrenje'),

    -- Admin schedule.
    ('admin.loginPrompt',             'en', 'Please log in to access admin.'),
    ('admin.loginPrompt',             'rs', 'Prijavite se da pristupite administraciji.'),
    ('admin.schedule.title',          'en', 'Schedule Management'),
    ('admin.schedule.title',          'rs', 'Upravljanje rasporedom'),
    ('admin.schedule.selectEmployee', 'en', 'Select Employee'),
    ('admin.schedule.selectEmployee', 'rs', 'Izaberite zaposlenog'),
    ('admin.schedule.selectPlaceholder','en', '-- Select --'),
    ('admin.schedule.selectPlaceholder','rs', '-- Izaberite --'),
    ('admin.schedule.weeklyHours',    'en', 'Weekly Working Hours'),
    ('admin.schedule.weeklyHours',    'rs', 'Nedeljno radno vreme'),
    ('admin.schedule.to',             'en', 'to'),
    ('admin.schedule.to',             'rs', 'do'),
    ('admin.schedule.saving',         'en', 'Saving...'),
    ('admin.schedule.saving',         'rs', 'Čuvanje...'),
    ('admin.schedule.saveHours',      'en', 'Save Working Hours'),
    ('admin.schedule.saveHours',      'rs', 'Sačuvaj radno vreme'),
    ('admin.schedule.saved',          'en', 'Working hours saved.'),
    ('admin.schedule.saved',          'rs', 'Radno vreme je sačuvano.'),
    ('admin.schedule.saveFailed',     'en', 'Failed to save.'),
    ('admin.schedule.saveFailed',     'rs', 'Čuvanje nije uspelo.'),
    ('admin.schedule.overrides',      'en', 'Date Overrides'),
    ('admin.schedule.overrides',      'rs', 'Izuzetci za datume'),
    ('admin.schedule.dayOff',         'en', 'Day off'),
    ('admin.schedule.dayOff',         'rs', 'Slobodan dan'),
    ('admin.schedule.overrideRemoved','en', 'Override removed.'),
    ('admin.schedule.overrideRemoved','rs', 'Izuzetak je uklonjen.'),
    ('admin.schedule.overrideRemoveFailed','en', 'Failed to remove override.'),
    ('admin.schedule.overrideRemoveFailed','rs', 'Uklanjanje izuzetka nije uspelo.'),
    ('admin.schedule.addOverride',    'en', 'Add Date Override'),
    ('admin.schedule.addOverride',    'rs', 'Dodaj izuzetak za datum'),
    ('admin.schedule.overrideAdded',  'en', 'Override added.'),
    ('admin.schedule.overrideAdded',  'rs', 'Izuzetak je dodat.'),
    ('admin.schedule.overrideAddFailed','en', 'Failed to add override.'),
    ('admin.schedule.overrideAddFailed','rs', 'Dodavanje izuzetka nije uspelo.'),
    ('admin.schedule.promptDate',     'en', 'Enter date (YYYY-MM-DD):'),
    ('admin.schedule.promptDate',     'rs', 'Unesite datum (GGGG-MM-DD):'),
    ('admin.schedule.promptDayOff',   'en', 'Is this a full day off? Click OK for yes, Cancel for no.'),
    ('admin.schedule.promptDayOff',   'rs', 'Da li je ovo ceo slobodan dan? Kliknite OK za da, Odustani za ne.'),
    ('admin.schedule.promptStart',    'en', 'Start time (HH:MM):'),
    ('admin.schedule.promptStart',    'rs', 'Vreme početka (HH:MM):'),
    ('admin.schedule.promptEnd',      'en', 'End time (HH:MM):'),
    ('admin.schedule.promptEnd',      'rs', 'Vreme kraja (HH:MM):'),
    ('admin.schedule.promptReason',   'en', 'Reason (optional):'),
    ('admin.schedule.promptReason',   'rs', 'Razlog (opciono):'),

    -- Admin services.
    ('admin.services.title',         'en', 'Service Management'),
    ('admin.services.title',         'rs', 'Upravljanje uslugama'),
    ('admin.services.schedule',      'en', 'Schedule'),
    ('admin.services.schedule',      'rs', 'Raspored'),
    ('admin.services.addTitle',      'en', 'Add Service'),
    ('admin.services.addTitle',      'rs', 'Dodaj uslugu'),
    ('admin.services.namePlaceholder','en', 'Haircut'),
    ('admin.services.namePlaceholder','rs', 'Šišanje'),
    ('admin.services.adding',        'en', 'Adding...'),
    ('admin.services.adding',        'rs', 'Dodavanje...'),
    ('admin.services.add',           'en', 'Add Service'),
    ('admin.services.add',           'rs', 'Dodaj uslugu'),
    ('admin.services.added',         'en', 'Service added.'),
    ('admin.services.added',         'rs', 'Usluga je dodata.'),
    ('admin.services.addFailed',     'en', 'Failed to add service.'),
    ('admin.services.addFailed',     'rs', 'Dodavanje usluge nije uspelo.'),
    ('admin.services.existing',      'en', 'Existing Services'),
    ('admin.services.existing',      'rs', 'Postojeće usluge'),
    ('admin.services.empty',         'en', 'No services yet.'),
    ('admin.services.empty',         'rs', 'Još nema usluga.'),
    ('admin.services.updated',       'en', 'Service updated.'),
    ('admin.services.updated',       'rs', 'Usluga je ažurirana.'),
    ('admin.services.updateFailed',  'en', 'Failed to update service.'),
    ('admin.services.updateFailed',  'rs', 'Ažuriranje usluge nije uspelo.'),
    ('admin.services.deleteFailed',  'en', 'Failed to delete service.'),
    ('admin.services.deleteFailed',  'rs', 'Brisanje usluge nije uspelo.'),
    ('admin.services.deleteConfirm', 'en', 'Delete this service?'),
    ('admin.services.deleteConfirm', 'rs', 'Obrisati ovu uslugu?'),
    ('admin.services.inactive',      'en', '(Inactive)'),
    ('admin.services.inactive',      'rs', '(Neaktivno)'),

    -- Reservations management.
    ('reservations.title',            'en', 'My Reservations'),
    ('reservations.title',            'rs', 'Moje rezervacije'),
    ('reservations.loginPrompt',      'en', 'Please log in to manage your reservations.'),
    ('reservations.loginPrompt',      'rs', 'Prijavite se da upravljate svojim rezervacijama.'),
    ('reservations.addAppointment',   'en', 'Add appointment'),
    ('reservations.addAppointment',   'rs', 'Dodaj termin'),
    ('reservations.reserveTime',      'en', 'Reserve time'),
    ('reservations.reserveTime',      'rs', 'Rezerviši vreme'),
    ('reservations.cancelled',        'en', 'Reservation cancelled.'),
    ('reservations.cancelled',        'rs', 'Rezervacija je otkazana.'),
    ('reservations.cancelFailed',     'en', 'Failed to cancel reservation.'),
    ('reservations.cancelFailed',     'rs', 'Otkazivanje rezervacije nije uspelo.'),
    ('reservations.noShowMarked',     'en', 'Appointment marked as no-show.'),
    ('reservations.noShowMarked',     'rs', 'Termin je označen kao nepojavljivanje.'),
    ('reservations.noShowFailed',     'en', 'Failed to mark no-show.'),
    ('reservations.noShowFailed',     'rs', 'Označavanje nepojavljivanja nije uspelo.'),
    ('reservations.accepted',         'en', 'Appointment accepted.'),
    ('reservations.accepted',         'rs', 'Termin je prihvaćen.'),
    ('reservations.acceptFailed',     'en', 'Failed to accept appointment.'),
    ('reservations.acceptFailed',     'rs', 'Prihvatanje termina nije uspelo.'),
    ('reservations.timeAccepted',     'en', 'Reserved time accepted.'),
    ('reservations.timeAccepted',     'rs', 'Rezervisano vreme je prihvaćeno.'),
    ('reservations.timeAcceptFailed', 'en', 'Failed to accept reserved time.'),
    ('reservations.timeAcceptFailed', 'rs', 'Prihvatanje rezervisanog vremena nije uspelo.'),
    ('reservations.rejected',         'en', 'Rejected.'),
    ('reservations.rejected',         'rs', 'Odbijeno.'),
    ('reservations.rejectFailed',     'en', 'Failed to reject.'),
    ('reservations.rejectFailed',     'rs', 'Odbijanje nije uspelo.'),
    ('reservations.employee',         'en', 'Employee'),
    ('reservations.employee',         'rs', 'Zaposleni'),
    ('reservations.customer',         'en', 'Customer'),
    ('reservations.customer',         'rs', 'Klijent'),
    ('reservations.service',          'en', 'Service'),
    ('reservations.service',          'rs', 'Usluga'),
    ('reservations.accept',           'en', 'Accept'),
    ('reservations.accept',           'rs', 'Prihvati'),
    ('reservations.reject',           'en', 'Reject'),
    ('reservations.reject',           'rs', 'Odbij'),
    ('reservations.cancel',           'en', 'Cancel'),
    ('reservations.cancel',           'rs', 'Otkaži'),
    ('reservations.noShow',           'en', 'No-show'),
    ('reservations.noShow',           'rs', 'Nepojavljivanje'),
    ('reservations.myAppointments',   'en', 'My appointments'),
    ('reservations.myAppointments',   'rs', 'Moji termini'),
    ('reservations.pendingApprovals', 'en', 'Pending approvals'),
    ('reservations.pendingApprovals', 'rs', 'Odobrenja na čekanju'),
    ('reservations.nothingToApprove', 'en', 'Nothing to approve.'),
    ('reservations.nothingToApprove', 'rs', 'Nema ništa za odobravanje.'),
    ('reservations.customerAppointments','en', 'Customer appointments'),
    ('reservations.customerAppointments','rs', 'Termini klijenata'),
    ('reservations.reservedTime',     'en', 'Reserved time'),
    ('reservations.reservedTime',     'rs', 'Rezervisano vreme'),
    ('reservations.cancelReservation','en', 'Cancel reservation'),
    ('reservations.cancelReservation','rs', 'Otkaži rezervaciju'),
    ('reservations.reasonRequired',   'en', 'Reason (required)'),
    ('reservations.reasonRequired',   'rs', 'Razlog (obavezno)'),
    ('reservations.cancelPlaceholder','en', 'Why are you cancelling?'),
    ('reservations.cancelPlaceholder','rs', 'Zašto otkazujete?'),
    ('reservations.cancelling',       'en', 'Cancelling…'),
    ('reservations.cancelling',       'rs', 'Otkazivanje…'),
    ('reservations.rejectPlaceholder','en', 'Why are you rejecting this?'),
    ('reservations.rejectPlaceholder','rs', 'Zašto odbijate ovo?'),
    ('reservations.rejecting',        'en', 'Rejecting…'),
    ('reservations.rejecting',        'rs', 'Odbijanje…'),
    ('reservations.noShowTitle',      'en', 'Mark as no-show?'),
    ('reservations.noShowTitle',      'rs', 'Označiti kao nepojavljivanje?'),
    ('reservations.markNoShow',       'en', 'Mark no-show'),
    ('reservations.markNoShow',       'rs', 'Označi nepojavljivanje'),

    -- Add appointment dialog.
    ('addAppointment.title',    'en', 'Add appointment'),
    ('addAppointment.title',    'rs', 'Dodaj termin'),
    ('addAppointment.choose',   'en', 'Choose a service and a time.'),
    ('addAppointment.choose',   'rs', 'Izaberite uslugu i vreme.'),
    ('addAppointment.failed',   'en', 'Failed to add appointment.'),
    ('addAppointment.failed',   'rs', 'Dodavanje termina nije uspelo.'),
    ('addAppointment.service',  'en', 'Service'),
    ('addAppointment.service',  'rs', 'Usluga'),
    ('addAppointment.date',     'en', 'Date'),
    ('addAppointment.date',     'rs', 'Datum'),
    ('addAppointment.time',     'en', 'Time'),
    ('addAppointment.time',     'rs', 'Vreme'),
    ('addAppointment.customer', 'en', 'Customer (optional)'),
    ('addAppointment.customer', 'rs', 'Klijent (opciono)'),
    ('addAppointment.noCustomer','en', 'No customer'),
    ('addAppointment.noCustomer','rs', 'Bez klijenta'),
    ('addAppointment.select',   'en', '-- Select --'),
    ('addAppointment.select',   'rs', '-- Izaberite --'),
    ('addAppointment.adding',   'en', 'Adding…'),
    ('addAppointment.adding',   'rs', 'Dodavanje…'),

    -- Create / rename salon.
    ('createSalon.nameLabel',      'en', 'Salon name'),
    ('createSalon.nameLabel',      'rs', 'Naziv salona'),
    ('createSalon.namePlaceholder','en', 'My Salon'),
    ('createSalon.namePlaceholder','rs', 'Moj salon'),
    ('createSalon.creating',       'en', 'Creating…'),
    ('createSalon.creating',       'rs', 'Kreiranje…'),
    ('createSalon.create',         'en', 'Create your first salon'),
    ('createSalon.create',         'rs', 'Kreirajte svoj prvi salon'),
    ('rename.title',           'en', 'Rename salon'),
    ('rename.title',           'rs', 'Preimenuj salon'),
    ('rename.help',            'en', 'Update the name shown to your customers.'),
    ('rename.help',            'rs', 'Ažurirajte naziv koji vide vaši klijenti.'),
    ('rename.namePlaceholder', 'en', 'Salon name'),
    ('rename.namePlaceholder', 'rs', 'Naziv salona'),
    ('rename.nameRequired',    'en', 'Name is required.'),
    ('rename.nameRequired',    'rs', 'Ime je obavezno.'),
    ('rename.failed',          'en', 'Failed to rename salon.'),
    ('rename.failed',          'rs', 'Preimenovanje salona nije uspelo.'),
    ('rename.saveName',        'en', 'Save name'),
    ('rename.saveName',        'rs', 'Sačuvaj naziv'),

    -- Salon policy.
    ('policy.title',              'en', 'Salon policy'),
    ('policy.title',              'rs', 'Politika salona'),
    ('policy.help',               'en', 'Booking rules, time slots and default working hours.'),
    ('policy.help',               'rs', 'Pravila rezervacije, termini i podrazumevano radno vreme.'),
    ('policy.cancellationNotice', 'en', 'Cancellation notice (hours before)'),
    ('policy.cancellationNotice', 'rs', 'Otkazni rok (sati unapred)'),
    ('policy.noShowGrace',        'en', 'No-show grace (hours after)'),
    ('policy.noShowGrace',        'rs', 'Grey period za nepojavljivanje (sati posle)'),
    ('policy.slotInterval',       'en', 'Time slot interval (minutes)'),
    ('policy.slotInterval',       'rs', 'Interval termina (minuti)'),
    ('policy.workingHours',       'en', 'Working hours'),
    ('policy.workingHours',       'rs', 'Radno vreme'),
    ('policy.cancellationInvalid','en', 'Cancellation notice must be zero or greater.'),
    ('policy.cancellationInvalid','rs', 'Otkazni rok mora biti nula ili veći.'),
    ('policy.noShowInvalid',      'en', 'No-show grace must be zero or greater.'),
    ('policy.noShowInvalid',      'rs', 'Grey period za nepojavljivanje mora biti nula ili veći.'),
    ('policy.intervalInvalid',    'en', 'Slot interval must be greater than zero.'),
    ('policy.intervalInvalid',    'rs', 'Interval termina mora biti veći od nule.'),
    ('policy.failed',             'en', 'Failed to save policy.'),
    ('policy.failed',             'rs', 'Čuvanje politike nije uspelo.'),
    ('policy.savePolicy',         'en', 'Save policy'),
    ('policy.savePolicy',         'rs', 'Sačuvaj politiku'),

    -- Onboarding gate.
    ('onboarding.pending', 'en', 'Your account is awaiting approval. Check back shortly.'),
    ('onboarding.pending', 'rs', 'Vaš nalog čeka odobrenje. Proverite uskoro.'),
    ('onboarding.setup',   'en', 'Set up your salon to continue.'),
    ('onboarding.setup',   'rs', 'Podesite svoj salon da nastavite.'),

    -- Scheduled panel.
    ('scheduled.title',    'en', 'Scheduled'),
    ('scheduled.title',    'rs', 'Zakazano'),
    ('scheduled.noEvents', 'en', 'No events scheduled.'),
    ('scheduled.noEvents', 'rs', 'Nema zakazanih događaja.'),
    ('scheduled.meetLink', 'en', 'Meet Link'),
    ('scheduled.meetLink', 'rs', 'Meet link'),
    ('scheduled.today',    'en', 'Go to today'),
    ('scheduled.today',    'rs', 'Idi na danas'),
    ('scheduled.prevDay',  'en', 'Previous day'),
    ('scheduled.prevDay',  'rs', 'Prethodni dan'),
    ('scheduled.nextDay',  'en', 'Next day'),
    ('scheduled.nextDay',  'rs', 'Sledeći dan'),

    -- Calendar controls.
    ('calendar.month',     'en', 'Month'),
    ('calendar.month',     'rs', 'Mesec'),
    ('calendar.year',      'en', 'Year'),
    ('calendar.year',      'rs', 'Godina'),
    ('calendar.prevMonth', 'en', 'Previous month'),
    ('calendar.prevMonth', 'rs', 'Prethodni mesec'),
    ('calendar.nextMonth', 'en', 'Next month'),
    ('calendar.nextMonth', 'rs', 'Sledeći mesec'),

    -- Theme toggle + image upload.
    ('theme.toggle',      'en', 'Toggle theme'),
    ('theme.toggle',      'rs', 'Promeni temu'),
    ('theme.light',       'en', 'Light'),
    ('theme.light',       'rs', 'Svetlo'),
    ('theme.dark',        'en', 'Dark'),
    ('theme.dark',        'rs', 'Tamno'),
    ('theme.system',      'en', 'System'),
    ('theme.system',      'rs', 'Sistem'),
    ('upload.working',    'en', 'Working…'),
    ('upload.working',    'rs', 'Obrađuje se…'),
    ('upload.camera',     'en', 'Camera'),
    ('upload.camera',     'rs', 'Kamera'),
    ('upload.uploadImage','en', 'Upload image'),
    ('upload.uploadImage','rs', 'Otpremi sliku'),

    -- Gallery lightbox.
    ('gallery.prev', 'en', 'Previous image'),
    ('gallery.prev', 'rs', 'Prethodna slika'),
    ('gallery.next', 'en', 'Next image'),
    ('gallery.next', 'rs', 'Sledeća slika'),

    -- Date picker page.
    ('datepicker.title',    'en', 'Select a Date'),
    ('datepicker.title',    'rs', 'Izaberite datum'),
    ('datepicker.selected', 'en', 'Selected: {date}'),
    ('datepicker.selected', 'rs', 'Izabrano: {date}'),

    -- Days of the week.
    ('days.sunday',    'en', 'Sunday'),
    ('days.sunday',    'rs', 'Nedelja'),
    ('days.monday',    'en', 'Monday'),
    ('days.monday',    'rs', 'Ponedeljak'),
    ('days.tuesday',   'en', 'Tuesday'),
    ('days.tuesday',   'rs', 'Utorak'),
    ('days.wednesday', 'en', 'Wednesday'),
    ('days.wednesday', 'rs', 'Sreda'),
    ('days.thursday',  'en', 'Thursday'),
    ('days.thursday',  'rs', 'Četvrtak'),
    ('days.friday',    'en', 'Friday'),
    ('days.friday',    'rs', 'Petak'),
    ('days.saturday',  'en', 'Saturday'),
    ('days.saturday',  'rs', 'Subota'),

    -- Months.
    ('months.january',   'en', 'January'),
    ('months.january',   'rs', 'Januar'),
    ('months.february',  'en', 'February'),
    ('months.february',  'rs', 'Februar'),
    ('months.march',     'en', 'March'),
    ('months.march',     'rs', 'Mart'),
    ('months.april',     'en', 'April'),
    ('months.april',     'rs', 'April'),
    ('months.may',       'en', 'May'),
    ('months.may',       'rs', 'Maj'),
    ('months.june',      'en', 'June'),
    ('months.june',      'rs', 'Jun'),
    ('months.july',      'en', 'July'),
    ('months.july',      'rs', 'Jul'),
    ('months.august',    'en', 'August'),
    ('months.august',    'rs', 'Avgust'),
    ('months.september', 'en', 'September'),
    ('months.september', 'rs', 'Septembar'),
    ('months.october',   'en', 'October'),
    ('months.october',   'rs', 'Oktobar'),
    ('months.november',  'en', 'November'),
    ('months.november',  'rs', 'Novembar'),
    ('months.december',  'en', 'December'),
    ('months.december',  'rs', 'Decembar');
