/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/business/{businessID}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all business users
         * @description Returns all business users for a business (admin only).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.BusinessUser"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a date override
         * @description Adds a working hours override (e.g. holiday) for an employee.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            /** @description Override details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.WorkingHoursOverride"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.WorkingHoursOverride"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/overrides/{overrideID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a date override
         * @description Removes a working hours override for an employee.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                    /** @description Override UUID */
                    overrideID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/working-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get employee working hours
         * @description Returns weekly working hours and date overrides for an employee.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.WorkingHoursResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Set employee working hours
         * @description Replaces the weekly working hours for an employee.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            /** @description Weekly working hours */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.SetWorkingHoursRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a service
         * @description Adds a new service to a business.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                };
                cookie?: never;
            };
            /** @description Service details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.Service"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Service"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/services/{serviceID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a service
         * @description Updates an existing service for a business.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description Service UUID */
                    serviceID: string;
                };
                cookie?: never;
            };
            /** @description Updated service details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.Service"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Service"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a service
         * @description Removes a service from a business.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description Service UUID */
                    serviceID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book an appointment
         * @description Creates a new appointment for the authenticated customer.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Appointment details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.CreateAppointmentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Appointment"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get business details
         * @description Returns a business with its services and employees by slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.BusinessResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List business employees
         * @description Returns all employees for a business.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.BusinessUser"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List business services
         * @description Returns all active services for a business.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Service"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available time slots
         * @description Returns available time slots for a service and employee on a given date.
         */
        get: {
            parameters: {
                query: {
                    /** @description Service UUID */
                    service_id: string;
                    /** @description Employee UUID */
                    employee_id: string;
                    /** @description Date (YYYY-MM-DD) */
                    date: string;
                };
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.SlotsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List customer appointments
         * @description Returns all appointments for the authenticated customer.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Appointment"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/appointments/{appointmentID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel an appointment
         * @description Cancels an appointment owned by the authenticated customer.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Appointment UUID */
                    appointmentID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "handler.BusinessResponse": {
            business: components["schemas"]["models.Business"];
            employees: components["schemas"]["models.BusinessUser"][];
            services: components["schemas"]["models.Service"][];
        };
        "handler.CreateAppointmentRequest": {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            business_id: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            business_user_id: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            service_id: string;
            /** @example 2024-01-01T09:00:00Z */
            start_time: string;
        };
        "handler.ErrorResponse": {
            /** @example error message */
            error: string;
        };
        "handler.MessageResponse": {
            /** @example operation complete */
            message: string;
        };
        "handler.SetWorkingHoursRequest": {
            working_hours: components["schemas"]["models.WorkingHours"][];
        };
        "handler.SlotsResponse": {
            /** @example 2024-01-01 */
            date: string;
            slots: components["schemas"]["models.TimeSlot"][];
        };
        "handler.WorkingHoursResponse": {
            overrides: components["schemas"]["models.WorkingHoursOverride"][];
            working_hours: components["schemas"]["models.WorkingHours"][];
        };
        "models.Appointment": {
            business_id: string;
            business_user_id: string;
            created_at: string;
            customer_user_id: string;
            end_time: string;
            id: string;
            service_id: string;
            start_time: string;
            /** @example confirmed */
            status: components["schemas"]["models.AppointmentStatus"];
        };
        /** @enum {string} */
        "models.AppointmentStatus": "confirmed" | "cancelled" | "completed" | "no_show";
        "models.Business": {
            created_at: string;
            id: string;
            /** @example Acme Spa */
            name: string;
            /** @example acme-spa */
            slug: string;
            updated_at: string;
        };
        "models.BusinessUser": {
            business_id: string;
            /** @example John Doe */
            display_name: string;
            id: string;
            /** @example admin */
            role: string;
            user_id: string;
        };
        "models.Service": {
            /** @example true */
            active: boolean;
            business_id: string;
            created_at: string;
            /** @example 60 */
            duration_minutes: number;
            id: string;
            /** @example Massage */
            name: string;
            /** @example 100 */
            price?: number;
        };
        "models.TimeSlot": {
            end_time: string;
            start_time: string;
        };
        "models.WorkingHours": {
            business_user_id?: string;
            /** @example 1 */
            day_of_week: number;
            /** @example 17:00 */
            end_time: string;
            id?: string;
            /** @example 09:00 */
            start_time: string;
        };
        "models.WorkingHoursOverride": {
            business_user_id?: string;
            /** @example 14:00 */
            end_time?: string;
            id?: string;
            /** @example false */
            is_off: boolean;
            /** @example 2024-12-25 */
            override_date: string;
            /** @example Christmas hours */
            reason?: string;
            /** @example 10:00 */
            start_time?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
