/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/business/{businessID}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all business users
         * @description Returns all business users for a business (admin only).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.BusinessUser"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an employee
         * @description Soft-deletes an employee: future reservations are reassigned or cancelled.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an employee avatar
         * @description Uploads an employee avatar (multipart file). Visibility is private; allowed for the employee or an admin.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["postApiAdminBusiness_businessid_employees_userid_image"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Image"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a date override
         * @description Adds a working hours override (e.g. holiday) for an employee.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            /** @description Override details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.WorkingHoursOverrideInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.WorkingHoursOverride"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/overrides/{overrideID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a date override
         * @description Removes a working hours override for an employee.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                    /** @description Override UUID */
                    overrideID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set employee services
         * @description Replaces the set of services an employee offers.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            /** @description Service IDs */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.SetEmployeeServicesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/unavailability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark an employee unavailable
         * @description Blocks a time range (e.g. vacation) for an employee.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            /** @description Unavailability range */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.CreateUnavailabilityRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.EmployeeUnavailability"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/unavailability/{unavailabilityID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an unavailability block
         * @description Deletes a previously created unavailability range.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                    /** @description Unavailability UUID */
                    unavailabilityID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/employees/{userID}/working-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get employee working hours
         * @description Returns weekly working hours and date overrides for an employee.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.WorkingHoursResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Set employee working hours
         * @description Replaces the weekly working hours for an employee.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description User ID (Keycloak sub) */
                    userID: string;
                };
                cookie?: never;
            };
            /** @description Weekly working hours */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.SetWorkingHoursRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a business image
         * @description Uploads a business hero/logo/background image (multipart file). Visibility is public.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** @description hero|logo|background (default hero) */
                        purpose?: string;
                        /**
                         * Format: binary
                         * @description Image file
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Image"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/images/{imageID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an image
         * @description Deletes an image. Admins delete the whole image; an employee may remove only their own avatar link.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description Image UUID */
                    imageID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a service
         * @description Adds a new service to a business.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                };
                cookie?: never;
            };
            /** @description Service details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.ServiceInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Service"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/services/{serviceID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a service
         * @description Updates an existing service for a business.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description Service UUID */
                    serviceID: string;
                };
                cookie?: never;
            };
            /** @description Updated service details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.ServiceInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Service"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a service
         * @description Removes a service from a business.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description Service UUID */
                    serviceID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/business/{businessID}/services/{serviceID}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a service picture
         * @description Uploads a service picture (multipart file). Visibility is public; services.picture_id is updated.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business UUID */
                    businessID: string;
                    /** @description Service UUID */
                    serviceID: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["postApiAdminBusiness_businessid_employees_userid_image"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Image"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book an appointment
         * @description Creates a new appointment for the authenticated customer.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Appointment details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.CreateAppointmentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Appointment"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get business details
         * @description Returns a business with its services and employees by slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.BusinessResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List business employees
         * @description Returns all employees for a business.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.BusinessUser"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List landing page sections
         * @description Returns the salon's landing page sections ordered by position.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Section"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List business services
         * @description Returns all active services for a business.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Service"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available time slots
         * @description Returns available time slots for a service and employee on a given date.
         */
        get: {
            parameters: {
                query: {
                    /** @description Service UUID */
                    service_id: string;
                    /** @description Employee UUID */
                    employee_id: string;
                    /** @description Date (YYYY-MM-DD) */
                    date: string;
                };
                header?: never;
                path: {
                    /** @description Business slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.SlotsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/i18n/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List UI labels for a locale
         * @description Returns the app's UI labels as a flat key/value object for the given locale.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Locale code (e.g. en, rs) */
                    locale: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.Translations"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{imageID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve an image
         * @description Public images are served directly; private images require auth and access (streamed through the API).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Image UUID */
                    imageID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user's onboarding state
         * @description Returns the caller's approval status, whether they already own a salon, and the businesses they belong to.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Me"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the caller's salon
         * @description Creates a business and the caller's owner (admin) row. Requires an approved account.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Business name */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.BusinessCreateInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Business"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List customer appointments
         * @description Returns all appointments for the authenticated customer.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.Appointment"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/appointments/{appointmentID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel an appointment
         * @description Cancels an appointment owned by the authenticated customer.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Appointment UUID */
                    appointmentID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "dto.Appointment": {
            business_id: string;
            business_user_id: string;
            cancellation_reason?: string;
            created_at: string;
            created_by: string;
            customer_user_id: string;
            end_time: string;
            id: string;
            service_id: string;
            start_time: string;
            status: string;
        };
        "dto.Business": {
            created_at: string;
            id: string;
            name: string;
            slug: string;
            updated_at: string;
        };
        "dto.BusinessUser": {
            active: boolean;
            business_id: string;
            display_name: string;
            id: string;
            role: string;
            user_id: string;
        };
        "dto.EmployeeUnavailability": {
            business_user_id: string;
            end_time: string;
            id: string;
            reason?: string;
            start_time: string;
        };
        "dto.Image": {
            content_type?: string;
            created_at: string;
            id: string;
            url: string;
        };
        "dto.Me": {
            approval_status: string;
            businesses: components["schemas"]["dto.MeBusiness"][];
            has_salon: boolean;
        };
        "dto.MeBusiness": {
            id: string;
            name: string;
            role: string;
            slug: string;
        };
        "dto.Section": {
            /** @description Content is a locale-keyed JSON object. */
            content?: Record<string, never>;
            id: string;
            page_id: string;
            position: number;
            type: string;
        };
        "dto.Service": {
            active: boolean;
            business_id: string;
            created_at: string;
            description?: string;
            duration_minutes: number;
            id: string;
            name: string;
            picture_id?: string;
            price?: number;
        };
        "dto.TimeSlot": {
            end_time: string;
            start_time: string;
        };
        "dto.WorkingHours": {
            business_user_id: string;
            day_of_week: number;
            end_time: string;
            id: string;
            start_time: string;
        };
        "dto.WorkingHoursOverride": {
            business_user_id: string;
            end_time?: string;
            id: string;
            is_off: boolean;
            override_date: string;
            reason?: string;
            start_time?: string;
        };
        "handler.BusinessCreateInput": {
            /** @example My Salon */
            name: string;
        };
        "handler.BusinessImages": {
            background?: string;
            hero?: string;
            logo?: string;
        };
        "handler.BusinessResponse": {
            business: components["schemas"]["dto.Business"];
            employees: components["schemas"]["dto.BusinessUser"][];
            images: components["schemas"]["handler.BusinessImages"];
            services: components["schemas"]["dto.Service"][];
        };
        "handler.CreateAppointmentRequest": {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            business_id: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            business_user_id: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            customer_user_id?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            service_id: string;
            /** @example 2024-01-01T09:00:00Z */
            start_time: string;
        };
        "handler.CreateUnavailabilityRequest": {
            /** @example 2024-01-01T17:00:00Z */
            end_time: string;
            /** @example Vacation */
            reason?: string;
            /** @example 2024-01-01T09:00:00Z */
            start_time: string;
        };
        "handler.ErrorResponse": {
            /** @example error message */
            error: string;
        };
        "handler.MessageResponse": {
            /** @example operation complete */
            message: string;
        };
        "handler.ServiceInput": {
            /** @example true */
            active: boolean;
            description?: string;
            /** @example 60 */
            duration_minutes: number;
            /** @example Massage */
            name: string;
            picture_id?: string;
            /** @example 100 */
            price?: number;
        };
        "handler.SetEmployeeServicesRequest": {
            /**
             * @example [
             *       "550e8400-e29b-41d4-a716-446655440000"
             *     ]
             */
            service_ids: string[];
        };
        "handler.SetWorkingHoursRequest": {
            working_hours: components["schemas"]["handler.WorkingHoursInput"][];
        };
        "handler.SlotsResponse": {
            /** @example 2024-01-01 */
            date: string;
            slots: components["schemas"]["dto.TimeSlot"][];
        };
        "handler.Translations": {
            [key: string]: string;
        };
        "handler.WorkingHoursInput": {
            /** @example 1 */
            day_of_week: number;
            /** @example 17:00 */
            end_time: string;
            /** @example 09:00 */
            start_time: string;
        };
        "handler.WorkingHoursOverrideInput": {
            /** @example 14:00 */
            end_time?: string;
            /** @example false */
            is_off: boolean;
            /** @example 2024-12-25 */
            override_date: string;
            /** @example Christmas hours */
            reason?: string;
            /** @example 10:00 */
            start_time?: string;
        };
        "handler.WorkingHoursResponse": {
            overrides: components["schemas"]["dto.WorkingHoursOverride"][];
            working_hours: components["schemas"]["dto.WorkingHours"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        postApiAdminBusiness_businessid_employees_userid_image: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Image file
                     */
                    file: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
